version: "3.9"

services:
  backend:
    image: quangllm/backend:latest
    container_name: backend-app
    ports:
      - "8000:8000"
    environment:
      - SOME_BACKEND_ENV=example_value
    restart: unless-stopped

  frontend:
    image: quangllm/front-end:latest
    container_name: frontend-app
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8000
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: mysql-dev
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=appuserpw
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uappuser", "-pappuserpw"]
      interval: 10s
      retries: 5
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data: